sudo: required
services:
 - docker
 
before_install:
 - docker build -t abhijitawachar/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run abhijitawachar/react-test npm test -- --coverage
 
after_success:
 - docker build -t abhijitawachar/multi-client ./client
 - docker build -t abhijitawachar/multi-nginx ./nginx
 - docker build -t abhijitawachar/multi-server ./server
 - docker build -t abhijitawachar/multi-worker ./worker 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push abhijitawachar/multi-client
 - docker push abhijitawachar/multi-nginx
 - docker push abhijitawachar/multi-server
 - docker push abhijitawachar/multi-worker
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 